### ISSUE TITLE
[Feature Request] Arm and Raspberry Support

### ISSUE THREAD

**Issue by corasaniti** [jordan-dalby/ByteStash#10]
Hi,

It would be nice to have a build for ARM architecture and be able to use it with a Raspberry
Thanks in advance
PC

**Comment by jordan-dalby** [comment]
> Hi,
> 
> It would be nice to have a build for ARM architecture and be able to use it with a Raspberry Thanks in advance PC

I've made an arm and raspi build, can you test it out?
ghcr.io/jordan-dalby/bytestash-dev:pr-12

**Comment by corasaniti** [comment]
It works perfectly on my Raspberry with Raspbian (Bookworm Based). 
I think you can merge it to the main branch
Thanks

PS: Can you add Dockerfile support in language?

![Immagine 2024-10-28 160134](https://github.com/user-attachments/assets/5b86feaf-f4de-425f-b4d8-4807d2be6b07)

![Immagine 2024-10-28 160157](https://github.com/user-attachments/assets/02bbe0bd-376e-4367-8b4a-2183ccfc7d71)

**Comment by corasaniti** [comment]
> > PS: Can you add Dockerfile support in language?
> 
> If you mean the actual Dockerfiles, that's already supported, just type "dockerfile" into the language box, it won't come up as a suggestion but it will work!
> 
> Is that what you mean?
Yes Thankyou
