### ISSUE TITLE
[BUG] Can't create snippet

### ISSUE THREAD

**Issue by Traxof63** [jordan-dalby/ByteStash#102]
**Describe the bug**
[ERROR] Error in POST /snippets: TypeError: SQLite3 can only bind numbers, strings, bigints, buffers, and null

**To Reproduce**
Create a new snippet

**Correction
FILE /server/src/repositories/snippetRepository.js
LINE 206 : `const insertResult = this.insertSnippetStmt.run(title, description, userId, isPublic ? 1 : 0);`

**Comment by jordan-dalby** [comment]
@Traxof63 
Seems like you're the unreleased version, did your database migrate correctly? Check the logs with DEBUG=true
