### ISSUE TITLE
[Feature Request] Swift syntax 

### ISSUE THREAD

**Issue by mkhasson97** [jordan-dalby/ByteStash#11]
I just installed the container on my Synology NAS and would love to (very appreciated) to have Swift syntax as well

**Comment by jordan-dalby** [comment]
> I just installed the container on my Synology NAS and would love to (very appreciated) to have Swift syntax as well

Hey!
You can add Swift by typing "swift" into the Language input box. Even if you don’t see any suggestions, it’ll still work, and Swift will appear as a suggestion in the future!
