### ISSUE TITLE
[FEATURE] BymeACoffe Link to support a bit 

### ISSUE THREAD

**Issue by funky123** [jordan-dalby/ByteStash#112]
A Way to buy some coffee to support a little bt

**Comment by jordan-dalby** [comment]
@funky123 
Hey! There's no obligation to donate, but if you do wish to, you can use this link: [ko-fi.com/zalosath](https://ko-fi.com/zalosath) :)

**Comment by funky123** [comment]
Ist there a way via PayPal ?

Diese E-Mail wurde von meinem Smartphone aus gesendet und beinhaltet daher nur das Nötigste.

Mit freundlichen Grüßen
Micha Welter
________________________________

**Comment by jordan-dalby** [comment]
@funky123 
Whoops! Check again, I updated the page :)
