### ISSUE TITLE
[BUG] Can't login after setting first default user/password

### ISSUE THREAD

**Issue by T-I-M-O-T** [jordan-dalby/ByteStash#116]
**Describe the bug**
Can't log-in after setting first default user/password. 
No login error message, but browser keeps being sent back to /login page.
No info in DEBUG, only SQL query.

**To Reproduce**
Firefox 132.0.2 / docker-compose / fresh install v1.5.1 / with empty data directory
```
services:
 ￼bytestash:
    image: "ghcr.io/jordan-dalby/bytestash:v1.5.1"
    restart: unless-stopped
    volumes:
      - /docker-data/bytestash-1.5.1:/data/snippets
    ​￼ports:
      - 4450:5000
    ​￼environment:
      - BASE_PATH=
      - JWT_SECRET=a[...]z
      - TOKEN_EXPIRY=24h
      - ALLOW_NEW_ACCOUNTS=true
      - DEBUG=true
```
- Set first user / passwd / passwd -> OK
- login submit -> no error displayed, browser sent back to /login

**Expected behavior**
User should be sent to the user's ByteStash home page upon login.

**Additional context**
data folder is populated properly with DB.
DEBUG only shows SQL queries but no error.

**Comment by jordan-dalby** [comment]
@T-I-M-O-T 
Are there any errors in F12? Specifically the network tab

**Comment by T-I-M-O-T** [comment]
I had a 401 on /snippets.
Made me think about the auth-basic I set on the caddy proxy... Once disabled, login is working fine.
Sorry for the false alarm :) And thanks for your reactivity !

**Comment by jordan-dalby** [comment]
> I had a 401 on /snippets.
> Made me think about the auth-basic I set on the caddy proxy... Once disabled, login is working fine.
> Sorry for the false alarm :) And thanks for your reactivity !

Ah! 1.5.2 will contain some fixes for Basic Auth compatibility, so if you want to re-enable it after it should work fine :)

**Comment by T-I-M-O-T** [comment]
Ok, I'll re-enable basic auth when deploying 1.5.2 and will come back here if anything is wrong with it :)
thanks !
