### ISSUE TITLE
[FEATURE] Option to disable standard login

### ISSUE THREAD

**Issue by WirtsLegs** [jordan-dalby/ByteStash#120]
**Is your feature request related to a problem? Please describe.**
Using Bytestash purely with OIDC users, there is no need for the option to login with user/pass

**Describe the solution you'd like**
Would like an option to disable the password login entirely and have the users only presented with the OIDC option(s).

**Describe alternatives you've considered**
Not really any alternatives, works fine as is but this would make it a bit cleaner for those not planning to use local users.

**Additional context**
No additional context to add

**Comment by jordan-dalby** [comment]
@WirtsLegs 
Should existing users still be able to sign into their accounts or should it totally disable local users?

**Comment by WirtsLegs** [comment]
> @WirtsLegs Should existing users still be able to sign into their accounts or should it totally disable local users?

I'd think it would totally disable local users, not even have the user/pass option on the page
