### ISSUE TITLE
[BUG] - DISABLE_INTERNAL_ACCOUNTS / DISABLE_ACCOUNTS seem to have no effect

### ISSUE THREAD

**Issue by jordanhandy** [jordan-dalby/ByteStash#127]
**Describe the bug**
`DISABLE_ACCOUNTS=true` appears to have no effect.  When set to `true`, still presented with the login screen on container redeploy

**To Reproduce**

Set Environment variable DISABLE_ACCOUNTS=true
Set Environment variable to DISABLE_INTERNAL_ACCOUNTS=true

Redeploy container and open Bytestash UI.  Still presented with login form

**Expected behavior**
Per documentation,
```
DISABLE_ACCOUNTS
true or false
Totally disable user accounts, any existing accounts will persist so you can switch back at any time
Acts as one user, you will be automatically authenticated as that user bypassing the login / registration screen

DISABLE_INTERNAL_ACCOUNTS
true or false
Disable internal accounts, this includes existing accounts
Useful if you only want SSO logins
```

Would like to totally disable the local (internal) account that was created on initial deploy and rely on OIDC only.
Local auth still possible even with both Env Vars = true

Also tried setting

`DISABLE_ACCOUNTS=false` and `DISABLE_INTERNAL_ACCOUNTS=true` (so that an OIDC account can still exist) seems to also have no effect

**Screenshots**

<img width="708" alt="image" src="https://github.com/user-attachments/assets/497dccf2-ba74-41a9-b393-9bf759eaac4d">

**Platform**
Docker, Alpine Linux

**Additional context**
ByteStash v 1.5.2

**Comment by jordan-dalby** [comment]
@jordanhandy 
Hi,
This will be in v1.5.3, which is not yet released.

If you want to rely on OIDC only, just use `DISABLE_INTERNAL_ACCOUNTS=true` (in v1.5.3), `DISABLE_ACCOUNTS=true` will disable _all_ accounts, meaning no OIDC either.

**Comment by jordanhandy** [comment]
Thanks. Will wait for next release.
