### ISSUE TITLE
[BUG]Authentication not working correctly

### ISSUE THREAD

**Issue by akalderon** [jordan-dalby/ByteStash#130]
**Describe the bug**
When logging in with the user/password that were created in 1.5.1 - first attempt getting invalid user/password.  second attempt with same credentials logs in but only after close to 30 seconds.  Also login screen takes about 20 seconds to just show up - this was not an issue with 1.5.1 yesterday.

**To Reproduce**
1. Upgrade docker container from 1.5.1 to 1.5.2
2. Attempt to log in - ~20 seconds for login to appear, first time logging in getting denied
3. Attempt to log in - second time with no change to the user/password fields (just clicking the login button second time) - login is successful but takes close to 30 seconds to get to the application main page
4. I only have one snippet for testing purposes so it cannot be a performance issue due to an overloaded database or CPU
5. This is true for both accessing via Traefik reverse-proxy as well as directly (http:<ip>:5000)

**Expected behavior**
1. Login page should appear instantaneously (takes about 20 seconds)
2. Login should go through on first attempt and application should perform as expected

**Screenshots**

**Platform**
Docker 27.2.0, build 3ab4256
Traefik reverse-proxy

**Additional context**
Issue started right after upgrading container from v1.5.1 to v1.5.2

**Comment by jordan-dalby** [comment]
@akalderon 
Any F12 errors?
If you enable debug `DEBUG=true` as an environment variable, are you getting any errors in the server console?

**Comment by akalderon** [comment]
For the oddest reason, changing Debug to true and restarting the container resolved the issue.  Flipping it back to false, the issue did not come back.  Something was definitely off and it just started to work fine.
Also from the logs when container was shutting down - perhaps related, perhaps not:
```
[INFO] Received shutdown signal, starting graceful shutdown...
file:///app/src/app.js:86
  shutdownDatabase();
  ^
ReferenceError: shutdownDatabase is not defined
    at process.handleShutdown (file:///app/src/app.js:86:3)
    at process.emit (node:events:517:28)
Node.js v18.20.5
```

**Comment by jordan-dalby** [comment]
@akalderon 
That's very weird! Debug is only used for logging :D Glad it's working now.

Yep thanks, that's fixed next update- shouldn't be a problem :)
