### ISSUE TITLE
[FEATURE] Shiki may be a good use here

### ISSUE THREAD

**Issue by Mateleo** [jordan-dalby/ByteStash#144]
Integrating [Shiki](https://shiki.style/) for syntax highlighting would greatly enhance the user experience when viewing code snippets !

**Comment by vlavrynovych** [comment]
As an alternative [the Prism](https://prismjs.com/) could be used. I added it my Ghost CMS blog and it was easy. I even have an [article about it](https://lavr.site/en-code-snippets-in-ghost/)

**Comment by vlavrynovych** [comment]
@Mateleo, what is wrong with already existing syntax highlighting?

Here is what I see in my current version of ByteStash v1.4.1 and overall I don't have any complains.
![Screenshot 2024-12-06 at 16 48 35](https://github.com/user-attachments/assets/babd63e1-36f7-4bcb-ae46-5b1c22aa4dc0)

**Comment by Mateleo** [comment]
@vlavrynovych Nothing wrong at all! The existing syntax highlighting is already great—very clear and effective. My suggestion for multi-theme support and hover types is more about adding a little extra customization and interactivity for users who enjoy tweaking their workspace or exploring type details on the fly. Totally optional, just a thought for the future!

**Comment by NeuroWinter** [comment]
Prism seems to be dead, and no long maintained. I think the original suggestion of integrating Shiki is a great idea, it will also include a lot of languages that are missing in Prism, like Elixir!

**Comment by jordan-dalby** [comment]
Shiki looks great! Even more so because it supports the Monaco editor (used by ByteStash). If someone wishes to implement this, go ahead, I might get to it at some point otherwise.
