### ISSUE TITLE
[BUG] OIDC Login no longer working 1.5.4

### ISSUE THREAD

**Issue by rolikeusch** [jordan-dalby/ByteStash#157]
**Describe the bug**

I'm no longer able to login with oidc in 1.5.4. I get the error:

`Cannot GET /api/auth/oidc/undefined/auth/callback`

the undefined part looks strange. also the url after redirect looks wired:

`https://<myurl>/api/auth/oidc/undefined/auth/callback?token=<token>`

are there some new changes in the oidc settings that I'm missing now?

**To Reproduce**

setup oidc and login

**Expected behavior**

login to the app.

**Screenshots**
N/A

**Platform**

Docker

**Additional context**

**Comment by jordan-dalby** [comment]
@rolikeusch 
Hey, that's odd. I believe that's the BASE_PATH. have you got that set anywhere?

**Comment by rolikeusch** [comment]
no, BASE_PATH is not set.

**Comment by jordan-dalby** [comment]
@rolikeusch 
Can you test out ghcr.io/jordan-dalby/bytestash:pr-158

**Comment by rolikeusch** [comment]
> @rolikeusch Can you test out ghcr.io/jordan-dalby/bytestash:pr-158

yes this version works.

**Comment by rolikeusch** [comment]
I have to admit  this BASE_PATH setting is still a mystery for me. not sure what I have to set there that this is working. at the moment I have it commented out in compose file, that way access to the website works.

I use a subdomain e.g. bytestash.example com, when I set the following I get only errors...

if set it to BASE_PATH="" I get: `Cannot GET /`
if set it to BASE_PATH="/" I get: `Cannot GET /`

**Comment by jordan-dalby** [comment]
@rolikeusch 
So for a subdomain, don't set it to anything, it's for when you want to do something like:
my.domain.io/bytestash
You would then set it to `/bytestash`
