### ISSUE TITLE
[BUG] OIDC with Pocket ID

### ISSUE THREAD

**Issue by Aloe-recite** [jordan-dalby/ByteStash#162]
**Describe the bug**
Whn using [Pocket ID](https://github.com/stonith404/pocket-id) as OIDC provider, login cannot be accomplished

**To Reproduce**
setup bytestash to OIDCS auth
setup pocket id following the guide
try to log in
check console: error 404 https://mypocketiddomain/api/oidc/authorize

**Expected behavior**
succesful login

**Screenshots**

**Platform**
Which platform are you using?
MacOS 15.2, Safari, docker in Debian VM

**Additional context**
Pocket ID has an authorization URL such as https://mypocketiddomain/authorize, bytestash seems to call https://mypocketiddomain/api/oidc/authorize and there is no way to configure a custom authorization URL

**Comment by jordan-dalby** [comment]
@Aloe-recite 
The auth URL is for ByteStash, not for Pocket ID, so that looks correct. Can I see your environment variables?

I don't know much about Pocket ID, does it use OpenID?

**Comment by jordan-dalby** [comment]
@Aloe-recite did you get this fixed?
