### ISSUE TITLE
[Other] Application SVG Logo for Dashboard Icons Repository

### ISSUE THREAD

**Issue by stuntguy3000** [jordan-dalby/ByteStash#163]
Hey there,

Is an SVG version of this project's logo available?

I'd love to add this project in to https://github.com/walkxcode/dashboard-icons, if possible!

Cheers

**Comment by jordan-dalby** [comment]
@stuntguy3000 
Hey!
Here's an SVG version of the logo.
![logo](https://github.com/user-attachments/assets/1299735d-5955-476e-8b96-b4e5e25adad2)
