### ISSUE TITLE
[FEATURE] User accounts

### ISSUE THREAD

**Issue by jordan-dalby** [jordan-dalby/ByteStash#25]
**Is your feature request related to a problem? Please describe.**
Users currently have to share the same instance of ByteStash, meaning all snippets are shared.

**Describe the solution you'd like**
Per user accounts.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jordan-dalby** [comment]
From Reddit:

- private and public snippets for each user
- SSO option
- potentially remote_user header. https://tools.ietf.org/html/rfc3875#section-4.1.11

**Comment by jordan-dalby** [comment]
Will probably be tricky to implement, will need to rethink the whole API flow.

**Comment by EDIflyer** [comment]
Appreciate may not be immediately possible but I like the idea of being able to share stashes to a group of users too - could be handy in teams.

**Comment by jordan-dalby** [comment]
Moving this up as it makes sense to implement this before other features.
