### ISSUE TITLE
[FEATURE] More filtering and ordering capabilities

### ISSUE THREAD

**Issue by Aloe-recite** [jordan-dalby/ByteStash#27]
**Is your feature request related to a problem? Please describe.**
I'd like to have more filtering and ordering capabilities, like filter by category, order alphabetically by name, orde by category, by language, and combo options.
I intend to archive many basic snippets considering that I'm a Linux total newbie, so being able to find them easily and quickly, also by intersecting filters, is a necessity.

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
As an alternative (more like a subsequent step), I'd love a small sidebar with the categories and maybe a snippet counter, the new snippet and settings button, and additional info like a GitHub link, version installed, update notifications and such.

**Additional context**
Nothing else! Great job so far!!!

**Comment by jordan-dalby** [comment]
@Aloe-recite 
Thanks for the suggestion!

For right now, you can filter by category by either-
1. Clicking on a category on a snippet (you can select multiple categories at once)
2. Using the search bar and prefixing your search with a #, for example #category will add that category to your current search.

Let me see what I can do about the rest!

**Comment by jordan-dalby** [comment]
@Aloe-recite 
I should make some documentation!

**Comment by jordan-dalby** [comment]
First pass: https://github.com/jordan-dalby/ByteStash/wiki
