### ISSUE TITLE
[FEATURE] Add Docker Secrets

### ISSUE THREAD

**Issue by gomeology** [jordan-dalby/ByteStash#45]
Implement docker secrets

**Comment by jordan-dalby** [comment]
@gomeology hi! Can you expand on this? Do you just want your code snippet to be "blurred" when there's a secret in it? Or something else?

**Comment by gomeology** [comment]
sorry was typing it from my phone... No i mean for the password/username/jwtticket. Be able to do jwt_FILE or something equivalent so it uses docker secrets when importing that environmental variable. so....
- AUTH_USERNAME=bytestash
- AUTH_PASSWORD=password
- JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp
Would turn into
environment:
    -AUTH_USERNAME_FILE: /run/secrets/username
    -AUTH_PASSWORD_FILE: /run/secrets/password
    - JWT_SECRET_FILE: /run/secrets/jwt
secrets:
-username
-password
-jwt

**Comment by jordan-dalby** [comment]
Accounts should be merged first, moved to 1.6.0
