### ISSUE TITLE
[BUG] Viewing snippet with long title overflows

### ISSUE THREAD

**Issue by Codycody31** [jordan-dalby/ByteStash#46]
**Describe the bug**
When viewing a snippet with a long title the text overflows,  just needs a `text-wrap: wrap;` on the `h2` element for the title, or the removal of `truncate`, as from what I can tell, actually makes it look worse, and doesn't work as expected.

**To Reproduce**
Create a snippet with a long name such as `Quickly configure the server with SSH and other standard applications`

**Screenshots**
![image](https://github.com/user-attachments/assets/110b540b-3e6a-4ca4-9a62-216a189b9761)

**Additional context**
**Version:** v1.4.1

**Comment by jordan-dalby** [comment]
Oops, thanks for the report!

**Comment by jordan-dalby** [comment]
Simplest fix is to add `truncate` here: https://github.com/jordan-dalby/ByteStash/blob/main/client/src/components/common/Modal.tsx#L45
Debating whether that's the best solution though, do we really want to truncate titles or do we want them to wrap?

**Comment by Harsha-Vardhan-24** [comment]
Hi @jordan-dalby, If this issue is not closed/sorted I would like to work on this issue.

**Comment by jordan-dalby** [comment]
@Harsha-Vardhan-24 please, go ahead!

**Comment by Codycody31** [comment]
It would probably be best to wrap the titles, given the user is expecting to see the full information from said snippet
