### ISSUE TITLE
[feature] custom categories

### ISSUE THREAD

**Issue by entnx-01** [jordan-dalby/ByteStash#5]
What do you think about adding custom categories to tag snippets? 

That would make it more easy to filter for the right snippet when using snippets of the same language in different contexts.

**Comment by jacobslusser** [comment]
Upvoting this request, but would suggest using a "tags" metaphor so that a snippet can belong to multiple categories. Great work on the project!

**Comment by jordan-dalby** [comment]
> What do you think about adding custom categories to tag snippets?
> 
> That would make it more easy to filter for the right snippet when using snippets of the same language in different contexts.

> Upvoting this request, but would suggest using a "tags" metaphor so that a snippet can belong to multiple categories. Great work on the project!
Thank you!

Working on it! :)

**Comment by jacobslusser** [comment]
As for implementation, I'll float another variation: using hashtags in the description field. 

Either way, as a dedicated field or hashtags, the key lift will be the ability to filter by tag.

**Comment by jordan-dalby** [comment]
> As for implementation, I'll float another variation: using hashtags in the description field. 
> 
> Either way, as a dedicated field or hashtags, the key lift will be the ability to filter by tag. 

You can actually already do this with the description, since the search bar can filter by description. I'll have a think about a good way to implement this but as an intermediate, description is a good shout!

**Comment by deuts** [comment]
Wish there will be tags as well.
