### ISSUE TITLE
Snippets not saved locally

### ISSUE THREAD

**Issue by ItsNoted** [jordan-dalby/ByteStash#6]
When I checked the mapped directory there is nothing in it. The snippets are shown on the web end though. It's not a permission issue but I'm wondering if the volume is mapped wrong in the compose?

**Comment by ArtisanByteCrafter** [comment]
I see the snippets saved in my mapped volume in `snippets.db`, a sqlite database.

**Comment by jordan-dalby** [comment]
> When I checked the mapped directory there is nothing in it. The snippets are shown on the web end though. It's not a permission issue but I'm wondering if the volume is mapped wrong in the compose?

Hi, make sure you configure the docker-compose to use the file path you want, specifically the volumes section.
    volumes:
      - "C:/my/path/snippets:/data/snippets"

**Comment by entnx-01** [comment]
I had the same issue when running master version. After changing to v1.1.0 the sql lite file is in the mapped folder.

**Comment by jordan-dalby** [comment]
@ItsNoted did you get this fixed?

**Comment by ItsNoted** [comment]
> @ItsNoted did you get this fixed?

Yes thanks. 1.1.0 works fine!
