### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by AlexTryHarder** [jordan-dalby/ByteStash#7]
Firstly - amazing project, finally I have safe place for my PowerShell scripts.
Is there any authentication on roadmap?

**Comment by jordan-dalby** [comment]
> Firstly - amazing project, finally I have safe place for my PowerShell scripts.
> Is there any authentication on roadmap? 
> 
> 

Hey, thank you!
It's something I've been thinking about. I've currently got it hidden behind Authelia but I can understand the need for separate authentication (perhaps multiple accounts on the same ByteStash instance?). I'll put it in the todo!

**Comment by jordan-dalby** [comment]
Hey @AlexTryHarder, I have implemented some basic authentication, you can test it if you like:
ghcr.io/jordan-dalby/bytestash-dev:pr-24

This is not the full user accounts implementation, I have created a separate ticket for that. #25
