### ISSUE TITLE
[BUG] VERY MINOR(!) - "Snippets loaded successfully" toast message displays twice each time the page loads

### ISSUE THREAD

**Issue by EDIflyer** [jordan-dalby/ByteStash#75]
**Describe the bug**
"Snippets loaded successfully" toast message displays twice each time the page loads

**To Reproduce**
Load the main page

**Expected behavior**
Only display the toast once

**Screenshots**
![Animation](https://github.com/user-attachments/assets/384b46ca-78cd-4cff-9bd0-fc705588b49d)

**Platform**
Windows 11/Chrome 131

**Additional context**
I'm also running Authelia/Nginx Proxy Manager - I suppose it could be related to that although I haven't noticed it with other containers?

In case they're relevant, there are two console errors:
```
Access to manifest at 'https://auth.ediflyer.tld/?rd=https://snippets.ediflyer.tld/manifest.json' (redirected from 'https://snippets.ediflyer.tld/manifest.json') from origin 'https://snippets.ediflyer.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
```
GET auth.ediflyer.tld/?rd=https://snippets.ediflyer.tld/manifest.json:1 
GET https://auth.ediflyer.tld/?rd=https://snippets.ediflyer.tld/manifest.json net::ERR_FAILED 200 (OK)
```

**Comment by jordan-dalby** [comment]
@EDIflyer 
Hey this is fixed now, it'll be in the next release. 

Careful not to reveal your domain (if it's public facing)!

**Comment by EDIflyer** [comment]
Oh fab, thanks @jordan-dalby 

Hehe, don't worry - I already tweaked it to a fake domain in my post 😉
