### ISSUE TITLE
[FEATURE] The snippets detail popup is too small

### ISSUE THREAD

**Issue by luowei** [jordan-dalby/ByteStash#79]
**The snippets detail popup is too small**
The snippets detail popup is too small, When there is a lot of content in a snippets, the popup for editing and viewing of the snippets is too small, which is inconvenient for viewing and editing.
<img width="1458" alt="image" src="https://github.com/user-attachments/assets/b9476c01-2cc2-4abc-a0cb-eb6bf5827fa3">

**Describe the solution you'd like**
1. I hope that the popup of edit and view of snippets can be changed to full screen size or replaced with a new page.
2. And a another desire is to hope the content in decription to support the markdown format, Thanks.

**Comment by jordan-dalby** [comment]
@luowei 
Hi,
The latest version (currently unreleased) has an option to open the full snippet in a new tab, with the same layout as the share menu. Does that work for you?

**Comment by luowei** [comment]
@jordan-dalby, It's better option can open the full snippet in a new tab, Thanks very much for your efforts.   And it would be nice to have full screen width for preview and editing on a widescreen device, and I eagerly await your adoption and update.
