### ISSUE TITLE
[FEATURE] Support markdown in Description

### ISSUE THREAD

**Issue by C493** [jordan-dalby/ByteStash#80]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it would be nice to have the description field support markdown.
Presently any lines entered are merged together (newlines removed) when viewing snippets.
Links are also not clickable.

**Describe the solution you'd like**
If the description field supported markdown, we could format the text and have clickable links.

**Describe alternatives you've considered**

**Additional context**
Awesome project, keep up the great work.

**Comment by vlavrynovych** [comment]
Hi @jordan-dalby 

+1 from me. I also wanted to add a nice looking description for another person. In particular I wanted to add a few links (each on the new line) and make some structure like paragraphs.
And as @C493 said, it's also not critical and just would be nice to have

**Comment by dhop90** [comment]
+1 for me as well
