### ISSUE TITLE
[FEATURE] - Add the Salesforce Apex language as available in snippet editor

### ISSUE THREAD

**Issue by jordanhandy** [jordan-dalby/ByteStash#87]
**Is your feature request related to a problem? Please describe.**
Feature request for additional language / syntax highlighting support- Salesforce Apex

**Describe the solution you'd like**
Salesforce Apex as a selectable language in the snippet editor, with syntax highlighting

**Describe alternatives you've considered**
Currently using Java in the interim

**Comment by jordan-dalby** [comment]
@jordanhandy 
Hi,
Apex is already a supported language, enter it as a custom language for now, just 'apex', I'll add it to the default list in the next update.
